# 1. Pytorch Basics

## 1-1 Basic configuration

### torch
* main namespace, various function are contained, similar to Numpy

### torch.autograd
* functions for computing gradients automatically.
* Could setup using enable_grad/no_grad
* contains Function class

### torch.nn
* Have various data structure and layers for neural network
* For instance, RNN, LSTM layers, activation function, loss function

### torch.optim
* implemented parameter optimization based on SGD

### torch.utils.data
* Have utils function for mini-batch in repetition SGD computation

### torch.onnx
* ONNX: Open Neural Network Exchange
* ONNX used as a format to export the model

## 1-2 Tensor Manipulation

### Goal
* understand vector, Matrix, Tensor
* How to use vector, Matrix and Tensor in Numpy and Pytorch

1. Vector, Matrix, Tensor
2. Numpy Review
3. PyTorch Tensor Allocation
4. Matrix Multiplication
5. Other Basic Ops

### 1. Vector, Matrix, Tensor

* Vector: 1차원으로 구성된 값 (x)
* Matrix: 2차원으로 구성된 값 (x, y)
* Tensor: 3차원 이상 구성된 값 (x, y ,z)

### 2. Make tensor from Numpy

In [1]:
import numpy as np

In [4]:
t = np.array([i for i in range(0,7)])
print(t)

[0 1 2 3 4 5 6]


* Rank: 현재 텐서의 차원
* shape: 크기

In [7]:
print("Rank of t: {}".format(t.ndim))
print("Shape of t: {}".format(t.shape))

Rank of t: 1
Shape of t: (7,)


In [9]:
for i in range(0,7):
  print(t[i])

0
1
2
3
4
5
6


In [10]:
print(t[2:5]) #slicing

[2 3 4]


In [11]:
t = np.array([[1,2], [3,4]])
print(t)

[[1 2]
 [3 4]]


In [12]:
print("Rank of t: {}".format(t.ndim))
print("Shape of t: {}".format(t.shape))

Rank of t: 2
Shape of t: (2, 2)


In [14]:
print(t[:,0])

[1 3]


### 3. Tensor from Pytorch 

In [15]:
import torch

In [19]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(type(t),t)

<class 'torch.Tensor'> tensor([0., 1., 2., 3., 4., 5., 6.])


In [20]:
print("Rank of t: ", t.dim())
print("Shape of t: ",t.shape)
print("size of t: ",t.size())

Rank of t:  1
Shape of t:  torch.Size([7])
size of t:  torch.Size([7])


In [21]:
print(t[2:5]) #slicing

tensor([2., 3., 4.])


In [22]:
t = torch.FloatTensor([
    [1.,2.,3.],
    [4.,5.,6.]
])
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [23]:
print(t.dim())
print(t.shape)

2
torch.Size([2, 3])


In [24]:
print(t[:,1])

tensor([2., 5.])


In [28]:
print(t[:,:-1]) # 마지막 열 빼고 모두 가져옴

tensor([[1., 2.],
        [4., 5.]])


### 3. Broadcasting
Pytorch automatically helps two different matrix to match size and compute operation

In [29]:
m1 = torch.FloatTensor([[3.,3.]])
m2= torch.FloatTensor([[2.,2.]])
print(m1+m2)

tensor([[5., 5.]])


In [30]:
# Vector + Scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1+m2)

tensor([[4., 5.]])


위의 예시를 보면 m1.shape = (1,2), m2.shape = (1)이므로 m2는 자동적으로 (1,2)가 되어 자신의 값을 복제하여 m1의 shape에 맞춰 더해진다.

In [31]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### 4. Frequently used utilities

**4-1 Matmul**

In [32]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2))
print(m1 @ m2)

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[ 5.],
        [11.]])


**4-2 element-wise multiplication**

In [33]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.mul(m2))
print(m1 * m2)

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


위의 곱셈은 element wise 곱을 수행하게 되는데 이때 broadcasting이 일어난 후, 각 원소끼리 곱하게 된다.

**4-3 mean**

In [34]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [35]:
t = torch.FloatTensor([
    [1, 2],
    [3, 4]
])

In [36]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


mean에 dim 인자를 줌으로써, 주어진 dim 인자는 차원을 잃게 된다. dim=0인 경우, 행의 의미는 사라지고 열만 판단하게 된다.

**4-4 sum**

In [37]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


**4-5 max, argmax**

In [41]:
print(t.max())
print(t.max(dim=-1))
print("t max value: ",t.max(dim=0)[0])
print("t argmax value: ",t.max(dim=0)[1])

tensor(4.)
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
t max value:  tensor([3., 4.])
t argmax value:  tensor([1, 1])


## 1-3 Tensor Manipulation2


**4-6 view**


Changing the size of Tensor without changing the number of elements

In [42]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [43]:
print(ft)
print(ft.view(-1,3))
print(t)
print(t.reshape(-1, 3))

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [44]:
print(ft.view(-1, 1, 3))
print(ft.view(-1, 1, 3).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


**4-7 squeeze**


remove dimension which is 1

In [46]:
ft = ft.view(-1, 1, 3)
print(ft)
print(ft.shape)
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


**4-8 Unsqueeze**


add dimension in a specific position

In [47]:
ft = ft.squeeze()
print(ft.shape)
print(ft.unsqueeze(1).shape)

torch.Size([4, 3])
torch.Size([4, 1, 3])


> view(), squeeze(), unsqueeze()는 텐서의 원소 수를 그대로 유지하면서 모양과 차원을 조절한다.

**4-8 Type Casting**



dtype을 선언할 때 텐서에 따라서 정의를 달리해준다.
![type casting](https://wikidocs.net/images/page/52846/newimage.png)

In [48]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [49]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [51]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


**4-9 concatenate**


torch를 연결하는 용도로 사용된다.
* dim: 연장시킬 차원을 선택한다.

In [54]:
x = torch.FloatTensor([[1, 2],[3, 4]])
y = torch.FloatTensor([[5, 6],[7, 8]])
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=-1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


**4-10 stacking**


쌓기
* dim: stacking할 matrix의 모양을 무시하고, 증가할 차원을 선택함
* 차원을 생각하지 않고 단순히 쌓는거여서 그림으로 그렸을 때 더욱 직관적임

In [55]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [56]:
print(torch.stack([x, y, z], dim=-1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


**4-11 ones_like, zeros_like**


1 또는 0으로 채워진 tensor 생성

In [57]:
x = torch.FloatTensor([[0, 1, 2], [3, 4, 5]])
print(x)

tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [60]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


위의 예시처럼 zeros_like 또는 ones_like의 인자로는 Tensor가 들어가야한다.

**4-12 In-place Operation(덮어쓰기 연산)**

In [61]:
x = torch.FloatTensor([
    [1, 2],
    [3, 4]
])

In [62]:
print(x.mul(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


위의 연산은 element-wise mul을 실행한 것이다.
연산 결과값은 실제 tensor(x)에 반영되지 않는다.

In [63]:
print(x.mul_(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


다음은 `mul_`을 사용하여 element-wise mul을 실행하였다. 뒤에 `_`를 붙여 연산 내용이 실제 tensor(x)에 반영되는 것을 확인할 수 있다.